//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermGuideWinForms
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PermGuideContainer : DbContext
    {
        public PermGuideContainer()
            : base("name=PermGuideContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Review> ReviewSet { get; set; }
        public virtual DbSet<MediaFile> MediaFileSet { get; set; }
        public virtual DbSet<Region> RegionSet { get; set; }
        public virtual DbSet<Timetable> TimetableSet { get; set; }
        public virtual DbSet<Content> ContentSet { get; set; }
    }
}
