//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermGuideWinForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; private set; }
        public System.DateTime CreationDate { get; set; }
        public int Mark { get; set; }
        public string Text { get; set; }
    
        public virtual User User { get; private set; }
        public virtual Content Content { get; private set; }
    }
}
