//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermGuideWinForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sight : Content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sight()
        {
            this.Excursion = new HashSet<Excursion>();
        }
    
        public string Location { get; private set; }
        public string Address { get; private set; }
    
        public virtual Region Region { get; private set; }
        public virtual Article Article { get; private set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Excursion> Excursion { get; private set; }
    }
}
